default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["DATABASE_USERNAME"] %>

development:
  <<: *default
  database: baseline_development
  host: localhost
  port: 5432
  pool: 5

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3


production:
  <<: *default
  database: baseline_production
